In [46]:
from keras.applications.inception_v3 import InceptionV3
from keras.preprocessing import image
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D
from keras import backend as K

from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Dropout, Activation, Flatten, Dense
from keras.callbacks import ModelCheckpoint, TensorBoard
import h5py
from keras import backend as K
import keras
import numpy as np

width, height = 150, 150

training_path = "/datasets/train"
val_path = "/datasets/validation"
# training_path = "trashnet_data/train"
# val_path = "trashnet_data/validation"
n_train = 2400
n_val = 400
epochs = 50
batch_size = 32

if K.image_data_format() =='channels_first':
    input_shape = (3, width, height)
else:
    input_shape = (width, height, 3)


# create the base pre-trained model
base_model = InceptionV3(weights=None, include_top=False)

# add a global spatial average pooling layer
x = base_model.output
x = GlobalAveragePooling2D()(x)
# let's add a fully-connected layer
x = Dense(1024, activation='relu')(x)
x = Dense(1024, activation='relu')(x)
# and a logistic layer -- let's say we have 200 classes
predictions = Dense(6, activation='softmax')(x)

# this is the model we will train
model = Model(inputs=base_model.input, outputs=predictions)


model.load_weights("trash-weights.hdf5")


In [47]:
from scipy import misc

image = misc.imread("paper571.jpg").reshape(1,384,512,3)

prediction = model.predict(image)

/Users/Ken/anaconda3/envs/practice/lib/python3.6/site-packages/ipykernel/__main__.py:3: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  app.launch_new_instance()


In [48]:
prediction

array([[ 0.,  0.,  0.,  0.,  0.,  1.]], dtype=float32)

In [49]:
prediction.argmax(axis=-1)

array([5])

In [50]:
import os
import os.path

In [51]:
for f in os.listdir("untitled folder"):
    print(f)
    image = misc.imread("untitled folder/" +f).reshape(1,512,384,3)

    prediction = model.predict(image)
    print(prediction)

glass1.jpg


/Users/Ken/anaconda3/envs/practice/lib/python3.6/site-packages/ipykernel/__main__.py:3: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  app.launch_new_instance()


[[ 0.  0.  0.  0.  0.  1.]]
glass10.jpg
[[ 0.  0.  0.  0.  0.  1.]]
glass2.jpg
[[ 0.  0.  0.  0.  0.  1.]]
glass3.jpg
[[ 0.  0.  0.  0.  0.  1.]]
glass4.jpg
[[ 0.  0.  0.  0.  0.  1.]]
glass5.jpg
[[ 0.  0.  0.  0.  0.  1.]]
glass6.jpg
[[ 0.  0.  0.  0.  0.  1.]]
glass7.jpg
[[ 0.  0.  0.  0.  0.  1.]]
glass8.jpg
[[ 0.  0.  0.  0.  0.  1.]]
glass9.jpg
[[ 0.  0.  0.  0.  0.  1.]]
